CREATE TABLE [dbo].[Booking] (
    [Id]            INT            NOT NULL PRIMARY KEY IDENTITY(86000,1),
    [CreatedBy]     NCHAR (50)     NOT NULL,
    [CreatedTime]   DATETIME       NOT NULL DEFAULT GETDATE(),
    [ModifiedTime]  DATETIME       NOT NULL DEFAULT GETDATE(),
    [BillToId]     INT            NOT NULL,
    [ShipperId]     INT            NOT NULL,
    [CarrierId]     INT            NOT NULL,
    [Vessel]        NVARCHAR (50)  NOT NULL,
    [VSL]           NCHAR (10)     NOT NULL,
    [Origin]      NVARCHAR (50)  NOT NULL,
    [Load]        NVARCHAR (50)  NOT NULL,
    [Discharge]   NVARCHAR (50)  NOT NULL,
    [Destination] NVARCHAR (50)  NOT NULL,
    [Commodity]     NVARCHAR (200) NULL,
    [Equiment]      NVARCHAR (100) NOT NULL,
    [Temp]          NCHAR (10)     NOT NULL,
    [Vents]         NCHAR (10)     NOT NULL,
    [Notes]         ntext NULL,
    [Status]		NCHAR(10) NULL, 
	CONSTRAINT [FK_Booking_BillTo] FOREIGN KEY ([BillToId]) REFERENCES [Company]([Id]),
	CONSTRAINT [FK_Booking_Shipper] FOREIGN KEY ([ShipperId]) REFERENCES [Company]([Id]),
	CONSTRAINT [FK_Booking_Carrier] FOREIGN KEY ([CarrierId]) REFERENCES [Company]([Id])
);

