//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingItem
    {
        public int Id { get; set; }
        public int BookingId { get; set; }
        public int CodeId { get; set; }
        public int Quantity { get; set; }
        public string Description { get; set; }
        public decimal BillingAmount { get; set; }
        public decimal PayoutAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual AccountingCode AccountingCode { get; set; }
        public virtual Booking Booking { get; set; }
    }
}
