//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.BillingItems = new HashSet<BillingItem>();
            this.Containers = new HashSet<Container>();
            this.Freights = new HashSet<Freight>();
            this.BookingReferences = new HashSet<BookingReference>();
        }
    
        public int Id { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public int BillToId { get; set; }
        public int ShipperId { get; set; }
        public string ShipperRefNo { get; set; }
        public int CarrierId { get; set; }
        public string CarrierRefNo { get; set; }
        public string Vessel { get; set; }
        public string Voyage { get; set; }
        public string Origin { get; set; }
        public string Load { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public string Discharge { get; set; }
        public string Destination { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public Nullable<System.DateTime> CutOffDate { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
        public Nullable<System.DateTime> CargoCut { get; set; }
        public Nullable<System.DateTime> VGM { get; set; }
        public string Commodity { get; set; }
        public string Equipment { get; set; }
        public string Temp { get; set; }
        public string Vents { get; set; }
        public string Notes { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillingItem> BillingItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Container> Containers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Freight> Freights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingReference> BookingReferences { get; set; }
        public virtual Company Company { get; set; }
        public virtual Company Company1 { get; set; }
        public virtual Company Company2 { get; set; }
    }
}
