//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingView
    {
        public int BookingId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<double> GiffiId { get; set; }
        public string BillTo { get; set; }
        public string ShipperRefNo { get; set; }
        public string CarrierCode { get; set; }
        public string CarrierRefNo { get; set; }
        public string Discharge { get; set; }
        public string Destination { get; set; }
        public Nullable<System.DateTime> CutOffDate { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public string Status { get; set; }
    }
}
