//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public int BillToId { get; set; }
        public int ShipperId { get; set; }
        public int CarrierId { get; set; }
        public string Vessel { get; set; }
        public string VSL { get; set; }
        public int OriginId { get; set; }
        public int LoadId { get; set; }
        public int DischargeId { get; set; }
        public int DestinationId { get; set; }
        public string Commodity { get; set; }
        public string Equiment { get; set; }
        public string Temp { get; set; }
        public string Vents { get; set; }
        public string Notes { get; set; }
        public string Status { get; set; }
    }
}
