//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Container
    {
        public int Id { get; set; }
        public string CarrierCode { get; set; }
        public int BookingId { get; set; }
        public decimal SealNumber { get; set; }
        public string ContainerNumber { get; set; }
        public double PackagesWeight { get; set; }
        public double NetWeight { get; set; }
        public string GRS { get; set; }
        public string Truck { get; set; }
        public string Invoice { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
