//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Container
    {
        public int Id { get; set; }
        public int BookingId { get; set; }
        public string ContainerNo { get; set; }
        public string SealNo { get; set; }
        public int NumOfPkgs { get; set; }
        public double NetWeight { get; set; }
        public float GRS { get; set; }
        public string Truck { get; set; }
        public long Invoice { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
